[package]
name = "assistant"
version = "0.1.0"
edition = "2024"

[dependencies]
hound = "3.5.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
whisper-rs = "0.14.2"
windows-sys = { version = "0.52.0", features = ["Win32_UI_Input_KeyboardAndMouse"] }
